import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clientUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
  const clientAnon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "";
  const serverUrl = process.env.SUPABASE_URL ?? clientUrl;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";
  const requireAdminBanner = (process.env.NEXT_PUBLIC_REQUIRE_ADMIN_ENVS || "").toLowerCase() === "true";

  const missingClientEnv = clientUrl === "" || clientAnon === "";
  const missingServerEnv = !missingClientEnv && (serverUrl === "" || serviceKey === "");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Dev-only env status helper */}
        {process.env.NODE_ENV !== "production" && (
          <div
            style={{
              position: "fixed",
              right: 12,
              bottom: 12,
              zIndex: 9999,
              background: "#111827",
              color: "#e5e7eb",
              border: "1px solid #374151",
              borderRadius: 8,
              padding: "6px 10px",
              fontSize: 12,
              boxShadow: "0 2px 8px rgba(0,0,0,0.25)",
            }}
          >
            <details>
              <summary style={{ cursor: "pointer", outline: "none" }}>Env status</summary>
              <div style={{ marginTop: 6, lineHeight: 1.5 }}>
                <div>
                  Client URL: {clientUrl ? "set" : "missing"}
                  {clientUrl ? ` (len ${clientUrl.length})` : ""}
                </div>
                <div>
                  Anon Key: {clientAnon ? "set" : "missing"}
                  {clientAnon ? ` (len ${clientAnon.length})` : ""}
                </div>
                <div>
                  Server URL: {serverUrl ? "set" : "missing"}
                  {serverUrl ? ` (len ${serverUrl.length})` : ""}
                </div>
                <div>
                  Service Role: {serviceKey ? "set" : "missing"}
                  {serviceKey ? ` (len ${serviceKey.length})` : ""}
                </div>
              </div>
            </details>
          </div>
        )}
        {process.env.NODE_ENV === "production" && missingClientEnv && (
          <div style={{
            background: "#fff3cd",
            color: "#664d03",
            border: "1px solid #f1e4a6",
            padding: "12px",
            margin: "0",
            textAlign: "center",
            fontSize: "14px",
          }}>
            Supabase environment variables are missing. Please set
            <code style={{ margin: "0 4px" }}>NEXT_PUBLIC_SUPABASE_URL</code>
            and
            <code style={{ margin: "0 4px" }}>NEXT_PUBLIC_SUPABASE_ANON_KEY</code>
            in your Vercel Project → Settings → Environment Variables, then redeploy.
          </div>
        )}
        {process.env.NODE_ENV === "production" && requireAdminBanner && missingServerEnv && (
          <div style={{
            background: "#e7f5ff",
            color: "#0b5ed7",
            border: "1px solid #b6dcff",
            padding: "10px",
            margin: "0",
            textAlign: "center",
            fontSize: "13px",
          }}>
            Server-side Supabase keys are missing. Set
            <code style={{ margin: "0 4px" }}>SUPABASE_URL</code>
            and
            <code style={{ margin: "0 4px" }}>SUPABASE_SERVICE_ROLE_KEY</code>
            in Vercel for admin operations to work, then redeploy.
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
